# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3411ec2f0bebbb00302f51c7c7b02bf2aa930a98702883d483907207e8ea5abf504ffc4b0708b2b36ea509fe2eedca28ca7fbfca1ae3529c159ea44811a88f5e

test:
  secret_key_base: 99af75308e190ad28b2ff4cf154956154d8881a0a1d3d9f686a838e50741db6f0c12c398cf2f01ff1663dd13d1435c70a5ce536c5cd9296bbe19e1b0e0bcfa3b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
